services:
  model-service:
    image: "${IMAGE_BACKEND}:${IMAGE_BACKEND_TAG}"
    container_name: model-service
    environment:
      - MODEL_DIR=${MODEL_DIR}
      - MODEL_FILENAME=${MODEL_FILENAME}
      - PREPROCESSOR_FILENAME=${PREPROCESSOR_FILENAME}
      - MODEL_URL=${MODEL_URL}
      - PREPROCESSOR_URL=${PREPROCESSOR_URL}
      - MODEL_PORT=${MODEL_PORT}
    volumes:
      - ./model-data:/root/sms/output
    expose:
      - "${MODEL_PORT}"
    restart: unless-stopped

  frontend:
    image: "${IMAGE_FRONTEND}:${IMAGE_FRONTEND_TAG}"
    container_name: frontend
    ports:
      - "${FRONTEND_HOST_PORT}:8080"
    environment:
      - MODEL_HOST=http://model-service:${MODEL_PORT}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - model-service
    restart: unless-stopped
