Vagrant.configure("2") do |config|
    # worker nodes
    workers = 2

    # base system required
    config.vm.box = "bento/ubuntu-24.04"

    # controller node
    config.vm.define "ctrl" do |node|
        node.vm.hostname = "ctrl"
        node.vm.network "private_network", ip: "192.168.56.100" 

        node.vm.provider "virtualbox" do |vb|
            vb.memory=4096 # 4GB
            vb.cpus=2
        end
    end

    # worker nodes
    (1..workers).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.hostname = "node-#{i}"
            node.vm.network "private_network", ip: "192.168.56.#{100 + i}"

            node.vm.provider "virtualbox" do |vb|
                vb.memory=6144 # 6GB
                vb.cpus=2
            end
        end
    end
    
    # Run Ansible on all machines
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/general.yaml"
        
        # passing worker count to Ansible
        ansible.extra_vars = {
            worker_count: workers
        }
    end


    config.vm.define "ctrl" do |node|
        node.vm.provision "ansible" do |ansible|
            ansible.playbook = "ansible/ctrl.yaml"
        end
    end

end
