N = 2  # number of worker nodes

Vagrant.configure("2") do |config|
  # Control node
  config.vm.define "ctrl" do |ctrl|
    ctrl.vm.box = "bento/ubuntu-24.04"
    ctrl.vm.box_version = "202510.26.0"
    ctrl.vm.hostname = "ctrl"

    ctrl.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end

    ctrl.vm.network "private_network", ip: "192.168.56.100"

    # General playbook (runs first)
    ctrl.vm.provision :ansible do |a|
      a.compatibility_mode = "2.0"
      a.playbook = "ansible/general.yaml"
    end

    # Controller-specific playbook (runs after)
    ctrl.vm.provision :ansible do |a|
      a.compatibility_mode = "2.0"
      a.playbook = "ansible/ctrl.yaml"
    end

  end

  # Worker nodes
  (1..N).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "bento/ubuntu-24.04"
      node.vm.box_version = "202510.26.0"
      node.vm.hostname = "node-#{i}"

      node.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
      end

      node.vm.network "private_network", ip: "192.168.56.#{100 + i}"

      # General playbook (common to all nodes)
      node.vm.provision :ansible do |a|
        a.compatibility_mode = "2.0"
        a.playbook = "ansible/general.yaml"
      end

      # Worker-specific playbook
      node.vm.provision :ansible do |a|
        a.playbook = "ansible/node.yaml"
        a.groups = {
          "workers" => ["node-1", "node-2"]
        }
      end
    end
  end
end
