{{- if and .Values.monitoring.enabled .Values.monitoring.alerts.email.enabled }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sms-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  route:
    groupBy: ["alertname"]
    groupWait: 30s
    groupInterval: 2m
    repeatInterval: 4h
    receiver: gmail-alerts
    routes:
      - matchers:
          - name: severity
            matchType: =
            value: warning
        receiver: gmail-alerts
  receivers:
    - name: gmail-alerts
      emailConfigs:
        - to: {{ .Values.monitoring.alerts.email.to | quote }}
          from: {{ .Values.monitoring.alerts.email.from | quote }}
          smarthost: "smtp.gmail.com:587"
          requireTLS: true
          authUsername: {{ .Values.monitoring.alerts.email.username | quote }}
          authPassword:
            name: sms-secrets
            key: smtp_pass
{{- end }}
