{{- if and .Values.monitoring.enabled .Values.monitoring.alerts.email.enabled }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: {{ .Values.namespaces.monitoring }}
  labels:
    release: {{ .Values.monitoring.prometheusRelease }}
spec:
  route:
    groupBy: ["alertname"]
    groupWait: 10s
    groupInterval: 1m
    repeatInterval: 1h
    receiver: gmail-alerts
    routes:
      - matchers:
          - name: severity
            matchType: =
            value: warning
        receiver: gmail-alerts
  receivers:
    - name: gmail-alerts
      emailConfigs:
        - to: {{ .Values.monitoring.alerts.email.to | quote }}
          from: {{ .Values.monitoring.alerts.email.from | quote }}
          smarthost: "smtp.gmail.com:587"
          requireTLS: true
          authUsername: {{ .Values.monitoring.alerts.email.username | quote }}
          authPassword:
            name: {{ .Values.secrets.smtp.existingSecret }}
            key: {{ .Values.secrets.smtp.passwordKey }}
{{- end }}
