apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-smtp
type: Opaque
stringData:
  username: {{ .Values.monitoring.alerts.email.username | quote }}
  password: {{ .Values.monitoring.alerts.email.password | quote }}