{{- if .Values.backend.shadow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}-shadow
  labels:
    app: {{ .Values.backend.name }}
    version: v3
spec:
  replicas: {{ .Values.backend.shadow.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
      version: v3
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        version: v3
    spec:
      volumes:
        - name: model-data
          hostPath:
            path: {{ .Values.backend.storage.hostPath }}
            type: DirectoryOrCreate

      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.shadowTag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
              name: {{ .Values.backend.service.portName }}

          envFrom:
            - configMapRef:
                name: {{ .Values.backend.name }}-config-shadow

          env:
            - name: MODEL_VERSION
              value: "v3"

          volumeMounts:
            - name: model-data
              mountPath: {{ .Values.backend.storage.mountPath | quote }}
{{- end }}
