apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}-canary
  labels:
    app: {{ .Values.backend.name }}
    version: v2
spec:
  replicas: {{ .Values.backend.canaryReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        version: v2
    spec:
    
      volumes:
        - name: model-data
          hostPath:
            path: {{ .Values.backend.storage.hostPath }}
            type: DirectoryOrCreate

      # -----------------------------
      # MAIN CONTAINERS
      # -----------------------------
      containers:
        # BACKEND CONTAINER
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.canaryTag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}   
              name: {{ .Values.backend.service.portName }}
              
          envFrom:
            - configMapRef:
                name: {{ .Values.backend.name }}-config

          env:
            - name: MODEL_VERSION
              value: "v2"

          volumeMounts:
            - name: model-data
              mountPath: {{ .Values.backend.model.dir | quote }}
