apiVersion: v1
kind: Service
metadata:
  name: sms-backend-svc
  labels:
    app: sms-backend
spec:
  selector:
    app: sms-backend
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
    name: metrics
  type: ClusterIP
