apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sms-backend
spec:
  hosts:
    - sms-backend-svc
  http:
    # frontend v1 → backend v1
    - match:
        - sourceLabels:
            app: sms-frontend
            version: v1
      route:
        - destination:
            host: sms-backend-svc
            subset: stable

    # frontend v2 → backend v2
    - match:
        - sourceLabels:
            app: sms-frontend
            version: v2
      route:
        - destination:
            host: sms-backend-svc
            subset: canary
