apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.name }}-config
data:
  MODEL_DIR: {{ .Values.backend.model.dir | quote }}
  MODEL_FILENAME: "{{ .Values.backend.model.filename }}"
  PREPROCESSOR_FILENAME: "{{ .Values.backend.model.preprocessorFilename }}"
  MODEL_URL: "{{ .Values.backend.model.url }}"
  PREPROCESSOR_URL: "{{ .Values.backend.model.preprocessorUrl }}"
  MODEL_PORT: "{{ .Values.backend.service.port }}"
