apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: sms-frontend
spec:
  host: sms-frontend-svc
  subsets:
  - name: stable
    labels:
      version: v1
  - name: canary
    labels:
      version: v2
