apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.name }}-config
data:
  MODEL_HOST: "http://{{ .Values.frontend.config.backendHost }}:{{ .Values.frontend.config.backendPort }}"
  SERVER_PORT: "{{ .Values.frontend.service.port }}"
