apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}
    version: v1
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
        version: v1
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.stableTag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.frontend.service.port }}
              name: {{ .Values.frontend.service.portName }}

          env:
            - name: APP_VERSION
              value: "v1" 
              
          envFrom:
            - configMapRef:
                name: {{ .Values.frontend.name }}-config

