apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: sms-frontend
spec:
  hosts:
    - "*"
  gateways:
    - sms-gateway
  http:

    - match:
        - headers:
            cookie:
              regex: ".*sms-user=stable.*"
      route:
        - destination:
            host: sms-frontend-svc
            subset: stable
      headers:
        request:
          set:
            x-app-version: "stable"
        response:
          set:
            version: "v1"

 
    - match:
        - headers:
            cookie:
              regex: ".*sms-user=canary.*"
      route:
        - destination:
            host: sms-frontend-svc
            subset: canary
      headers:
        request:
          set:
            x-app-version: "canary"
        response:
          set:
            version: "v2"

    # First-time users → 90/10
    - route:
        - destination:
            host: sms-frontend-svc
            subset: stable
          weight: 90
          headers:
            response:
              add:
                Set-Cookie: "sms-user=stable; Path=/"

        - destination:
            host: sms-frontend-svc
            subset: canary
          weight: 10
          headers:
            response:
              add:
                Set-Cookie: "sms-user=canary; Path=/"
