apiVersion: v1
kind: Service
metadata:
  name: sms-frontend-svc
  labels:
    app: sms-frontend
spec:
  selector:
    app: sms-frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
    name: http
  type: ClusterIP
