apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}-canary
  labels:
    app: {{ .Values.frontend.name }}
    version: v2
spec:
  replicas: {{ .Values.frontend.canaryReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
        version: v2
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.canaryTag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.frontend.service.port }}
            name: {{ .Values.frontend.service.portName }}

          env:
            - name: APP_VERSION
              value: "v2"

          envFrom:
            - configMapRef:
                name: {{ .Values.frontend.name }}-config

          