apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.istio.ingressGateway.name }}
spec:
  selector:
    istio: {{ .Values.istio.ingressGateway.selector }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.ingress.host.primary | quote }}
        - {{ .Values.ingress.host.stable | quote }}
        - {{ .Values.ingress.host.canary | quote }}