{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.frontend.name }}-sm
  namespace: {{ .Values.namespaces.monitoring }}
  labels:
    release: {{ .Values.monitoring.prometheusRelease }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  namespaceSelector:
    any: true
  endpoints:
    - port: {{ .Values.frontend.service.portName }}
      path: /metrics
      interval: 30s
{{- end }}

