{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sms-backend-sm
  namespace: monitoring
  labels:
    release: {{ .Values.monitoring.prometheusRelease }}
spec:
  selector:
    matchLabels:
      app: sms-backend
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
{{- end }}
