{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sms-backend-rules
  namespace: monitoring
  labels:
    release: {{ .Values.monitoring.prometheusRelease }}
spec:
  groups:
  - name: sms.rules
    rules:
    - alert: HighRequestRate
      expr: increase(sms_requests_total[1m]) > 15
      for: 1m
      labels:
        severity: warning
        namespace: monitoring   # <--- REQUIRED TO MATCH CONFIG
      annotations:
        summary: "High request rate on SMS frontend"
        description: "More than ~15 requests/min for 1 minutes"
{{- end }}
