{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sms-frontend-rules
  namespace: {{ .Values.global.namespaces.monitoring }}
  labels:
    release: {{ .Values.monitoring.prometheusRelease }}
spec:
  groups:
  - name: sms.frontend.rules
    rules:
    - alert: HighFrontendRequestRate
      expr: |
        sum by (version) (
          rate(sms_requests_total[2m])
        ) > 0.25
      for: 2m
      labels:
        severity: warning
        namespace: default
      annotations:
        summary: "High request rate on SMS frontend ({{`{{`}} $labels.version {{`}}`}})"
        description: |
          Frontend version {{`{{`}} $labels.version {{`}}`}} is receiving
          more than ~15 requests per minute for 2 minutes.
{{- end }}
