{{- if .Values.monitoring.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sms-frontend-sm
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sms-frontend
  namespaceSelector:
    any: true
  endpoints:
    - port: http            
      path: /metrics
      interval: 30s

{{- end }}

