{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: sms-secrets
type: Opaque
stringData:
  smtp_user: {{ .Values.secrets.smtp_user | quote }}
  smtp_pass: {{ .Values.secrets.smtp_pass | quote }}
{{- end }}
